name: Docker Image CI

on: [push]

jobs:

#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build and tag image
      run: docker build -t "docker.pkg.github.com/$GITHUB_REPOSITORY/docker-webdav:latest" -f Dockerfile .

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $PUBLISH_TOKEN
      env:
        PUBLISH_TOKEN: ${{secrets.PUBLISH_TOKEN}}

    - name: Publish to GPR
      run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/docker-webdav:latest"
